// redux 이벤트 처리 저장
// 서버 상태 이벤트 처리
export const UPDATE_HOST_STATUS = "UPDATE_HOST_STATUS";
export const UPDATE_STORAGE_USAGE = "UPDATE_STORAGE_USAGE";
export const UPDATE_YARN_JOB_LIST = "UPDATE_YARN_JOB_LIST";
export const UPDATE_YARN_STATUS = "UPDATE_YARN_STATUS";
export const UPDATE_YARN_JOB_MONITOR_LIST = "UPDATE_YARN_JOB_MONITOR_LIST";

export const UPDATE_ALERT_LIST = "UPDATE_ALERT_LIST";
